
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrest
    username: postgres
    password: 1111
  jpa:
    generate-ddl: true
  flyway:
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-nwxbmgmx1lcshk46.us.auth0.com/"
logging:
  level:
    org.springframework.security: debug
okta:
  oauth2:
    issuer: https://dev-nwxbmgmx1lcshk46.us.auth0.com/
    audience: http://localhost:8080/